version: 0.0
os: linux
files:
  - source: app/build/libs/app.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy-scripts/compile_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root
