name: Deploy AWS cloudformation stack

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ secrets.Region }}
          aws-access-key-id: ${{ secrets.AccessKeyId }}
          aws-secret-access-key: ${{ secrets.SecretAccessKey }}
          aws-session-token: ${{ secrets.SessionToken }}

      - name: Deploy to AWS CloudFormation
        if: env.WORKFLOW_SETUP_DONE == 'false'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: tomcat
          template: stack.yml
      - name: Change env variable
        if: env.WORKFLOW_SETUP_DONE == 'false'
        run: echo "WORKFLOW_SETUP_DONE=true" >> $GITHUB_ENV
