name: Deploy code with aws codedeploy

on:
  workflow_run:
    workflows:
      ["Java Test and Build with Gradle", "Deploy AWS cloudformation stack"]
    types:
      - completed

  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Wait for Java Test and Build with Gradle to succeed
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          check-name: "Wait for Backend Main Pipeline"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for Deploy AWS cloudformation stack to succeed
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          check-name: "Deploy AWS cloudformation stack"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ secrets.Region }}
          aws-access-key-id: ${{ secrets.AccessKeyId }}
          aws-secret-access-key: ${{ secrets.SecretAccessKey }}
          aws-session-token: ${{ secrets.SessionToken }}
      - name: "Deploy code"
        run: aws deploy create-deployment --application-name "TomcatApplication" --deployment-group-name "TomcatDeploymentGroup" --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
